spring:
  application:
    name: dayone-financial

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generater-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dayone;DB_CLOSE_DELAY=-1
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWpdmlkZW5kLXByb2plY3QtdHV0bj#pYWwtand)LXNlY3JldC1rZXkK

  main:
    allow-bean-definition-overriding: true

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"